services:
  - type: web
    name: lakes-of-grace-resort-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
